spring:
  datasource:
    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql
      # 필요 시 드롭 스크립트도 함께:
      # data-locations: classpath:org/springframework/batch/core/schema-drop-h2.sql

  batch:
    jdbc:
      initialize-schema: never   # ⭐ 중복 생성 방지
    job:
      enabled: false

  kafka:
    bootstrap-servers: localhost:9092
